# Generated by Django 5.2.17 on 2026-08-07 11:55

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='currency',
            field=models.CharField(default='PKR', max_length=3),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_closes_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_enabled',
            field=models.BooleanField(default=False, help_text='Master switch. Registration is closed unless this is ticked.'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_hold_minutes',
            field=models.PositiveIntegerField(default=1440, help_text='How long an unpaid registration holds a seat before the seat is released. 0 means a pending registration holds its seat forever.'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_opens_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_prefix',
            field=models.CharField(blank=True, help_text='Ticket numbers look like TEDX2026-0001. Leave blank to derive from the year.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='ticket_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Set to 0 for a free event — tickets are then issued instantly.', max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
