# Generated by Django 5.2.17 on 2026-08-10 01:10

import apps.ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0003_ticketsequence_prefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('provider', models.CharField(choices=[('easypaisa', 'Easypaisa'), ('jazzcash', 'JazzCash'), ('bank', 'Bank transfer'), ('other', 'Other')], max_length=20)),
                ('account_title', models.CharField(help_text='The name the account is registered under — attendees check this before sending.', max_length=150)),
                ('account_number', models.CharField(help_text='Wallet number, or account number for a bank.', max_length=60)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('iban', models.CharField(blank=True, max_length=40)),
                ('note', models.CharField(blank=True, help_text='Optional extra instruction, e.g. "send as a personal transfer, not a bill payment".', max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Payment Account',
                'verbose_name_plural': 'Payment Accounts',
                'ordering': ['order', 'provider'],
            },
        ),
        migrations.AddField(
            model_name='order',
            name='paid_from_number',
            field=models.CharField(blank=True, help_text='The wallet or account number the attendee paid from.', max_length=30),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot of the transfer. Staff-only — never exposed publicly.', upload_to=apps.ticketing.models.payment_proof_path),
        ),
        migrations.AddField(
            model_name='order',
            name='proof_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='reference',
            field=models.CharField(blank=True, help_text='Transaction ID from the transfer, or the gateway reference.', max_length=120),
        ),
    ]
