# Generated by Django 5.2.17 on 2026-08-11 00:46

import apps.common.storages
import apps.ticketing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing', '0004_paymentaccount_order_paid_from_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, help_text='Screenshot of the transfer. Staff-only — never exposed publicly.', storage=apps.common.storages.private_media_storage, upload_to=apps.ticketing.models.payment_proof_path),
        ),
    ]
