# Generated by Django 5.2.17 on 2026-08-11 04:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_currency_event_registration_closes_at_and_more'),
        ('ticketing', '0005_alter_order_payment_proof'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='registration',
            index=models.Index(fields=['user'], name='ticketing_r_user_id_09f187_idx'),
        ),
    ]
