# Generated by Django 6.0.8 on 2026-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order', 'question'],
            },
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('eyebrow', models.CharField(default='TEDxUMT Lahore \xa0·\xa0 University of Management and Technology', max_length=200)),
                ('headline_line1', models.CharField(default='Ideas worth', max_length=100)),
                ('headline_line2', models.CharField(default='spreading.', max_length=100)),
                ('subheading', models.TextField(default='An independently organized TED event bringing Lahore’s boldest thinkers, builders, and storytellers to one stage.')),
                ('cta_primary_label', models.CharField(default='Register', max_length=50)),
                ('cta_primary_url', models.CharField(default='/apply', max_length=200)),
                ('cta_secondary_label', models.CharField(default='Become a Speaker', max_length=50)),
                ('cta_secondary_url', models.CharField(default='/apply', max_length=200)),
                ('background_image', models.ImageField(blank=True, help_text='Recommended: 1920×1080px or wider. Replaces the campus background.', upload_to='hero/')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Section',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NavigationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('label', models.CharField(max_length=50)),
                ('url', models.CharField(max_length=200)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('open_in_new_tab', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Navigation Item',
                'verbose_name_plural': 'Navigation Items',
                'ordering': ['order', 'label'],
            },
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('twitter', 'Twitter / X'), ('tiktok', 'TikTok'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField()),
                ('display_label', models.CharField(help_text='Short label shown in footer badge (e.g. IG, in, FB, YT)', max_length=10)),
                ('aria_label', models.CharField(blank=True, max_length=50)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Social Link',
                'verbose_name_plural': 'Social Links',
                'ordering': ['order', 'platform'],
            },
        ),
        migrations.CreateModel(
            name='WebsiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('site_name', models.CharField(default='TEDxUMT Lahore', max_length=100)),
                ('tagline', models.CharField(default='Ideas Worth Spreading', max_length=200)),
                ('description', models.TextField(default='An independently organized TED event at the University of Management and Technology.')),
                ('events_count', models.CharField(default='3', max_length=20)),
                ('speakers_count', models.CharField(default='30+', max_length=20)),
                ('attendees_count', models.CharField(default='4,200+', max_length=20)),
                ('about_summary', models.TextField(default="Founded in December 2025, TEDxUMT Lahore is the University of Management and Technology's first officially licensed TEDx organization. Inspired by Ideas Worth Spreading, we bring together innovators, creators, and changemakers to share ideas that inspire, connect, and create meaningful impact.")),
                ('email', models.EmailField(default='tedxumtlahore@umt.edu.pk', max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(default='UMT Campus, C-II, Johar Town, Lahore', max_length=300)),
                ('map_embed_url', models.URLField(blank=True)),
                ('copyright_text', models.CharField(default='This independent TEDx event is operated under license from TED.', max_length=300)),
                ('footer_tagline', models.CharField(default="Bringing ideas worth spreading to Lahore's brightest minds since 2025.", max_length=300)),
                ('ted_event_url', models.URLField(blank=True, default='https://www.ted.com/tedx/events/69864')),
            ],
            options={
                'verbose_name': 'Website Settings',
                'verbose_name_plural': 'Website Settings',
                'ordering': ['-created_at'],
            },
        ),
    ]
