# Generated by Django 5.2.17 on 2026-08-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('description', models.TextField(blank=True, help_text='What this package includes — shown on the Sponsors page.')),
                ('benefits', models.TextField(blank=True, help_text='One benefit per line. Rendered as a list on the website.')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower numbers rank higher (Title = 0, Gold = 1, ...).')),
                ('is_visible', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sponsor Tier',
                'verbose_name_plural': 'Sponsor Tiers',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('logo', models.ImageField(blank=True, help_text='Transparent PNG or SVG works best. Falls back to the name in text.', upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('event', models.ForeignKey(blank=True, help_text='Optional — which edition this organization sponsored.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsors', to='events.event')),
                ('tier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsors', to='sponsors.sponsortier')),
            ],
            options={
                'verbose_name': 'Sponsor',
                'verbose_name_plural': 'Sponsors',
                'ordering': ['tier__order', 'order', 'name'],
            },
        ),
    ]
