# Generated by Django 5.2.17 on 2026-08-06 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Private — never exposed through the API.')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NewsletterSubscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(blank=True, max_length=150)),
                ('is_subscribed', models.BooleanField(default=True)),
                ('unsubscribed_at', models.DateTimeField(blank=True, null=True)),
                ('source', models.CharField(default='website', help_text='Where the signup came from (website, event, import, ...).', max_length=50)),
            ],
            options={
                'verbose_name': 'Newsletter Subscriber',
                'verbose_name_plural': 'Newsletter Subscribers',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartnerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Private — never exposed through the API.')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('organization_name', models.CharField(max_length=200)),
                ('contact_person', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('website', models.URLField(blank=True)),
                ('partnership_type', models.CharField(choices=[('sponsor', 'Sponsor'), ('media', 'Media Partner'), ('community', 'Community Partner'), ('venue', 'Venue Partner'), ('other', 'Other')], default='sponsor', max_length=20)),
                ('proposal', models.TextField(help_text='What kind of partnership do you have in mind?')),
            ],
            options={
                'verbose_name': 'Partner Application',
                'verbose_name_plural': 'Partner Applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SpeakerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Private — never exposed through the API.')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('designation', models.CharField(blank=True, max_length=200)),
                ('talk_title', models.CharField(max_length=200)),
                ('talk_summary', models.TextField(help_text='What is the idea worth spreading?')),
                ('previous_experience', models.TextField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Optional link to a previous talk or an audition video.')),
            ],
            options={
                'verbose_name': 'Speaker Application',
                'verbose_name_plural': 'Speaker Applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('in_review', 'In Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('archived', 'Archived')], default='new', max_length=20)),
                ('internal_notes', models.TextField(blank=True, help_text='Private — never exposed through the API.')),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('university', models.CharField(blank=True, max_length=200)),
                ('student_id', models.CharField(blank=True, max_length=50)),
                ('preferred_department', models.CharField(blank=True, help_text='Free text — e.g. Marketing, Operations, Design.', max_length=100)),
                ('availability', models.CharField(choices=[('event_day', 'Event Day Only'), ('part_time', 'Part Time (Year Round)'), ('full_time', 'Full Time (Year Round)')], default='event_day', max_length=20)),
                ('skills', models.TextField(blank=True)),
                ('motivation', models.TextField(help_text='Why do you want to join?')),
            ],
            options={
                'verbose_name': 'Volunteer Application',
                'verbose_name_plural': 'Volunteer Applications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
