# Generated by Django 5.2.17 on 2026-08-06 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('sponsors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnerapplication',
            name='interested_tier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='partner_applications', to='sponsors.sponsortier'),
        ),
    ]
