# Generated by Django 6.0.8 on 2026-08-04 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('section_key', models.CharField(choices=[('what_is_ted', 'What is TED?'), ('what_is_tedx', 'What is TEDx?'), ('our_story', 'Our Story'), ('mission', 'Our Mission'), ('vision', 'Our Vision')], max_length=30, unique=True)),
                ('eyebrow', models.CharField(blank=True, max_length=100)),
                ('heading', models.CharField(max_length=300)),
                ('body', models.TextField()),
                ('image', models.ImageField(blank=True, help_text='Section image. Will be displayed beside the text.', upload_to='about/')),
                ('image_position', models.CharField(choices=[('left', 'Image on Left'), ('right', 'Image on Right')], default='right', max_length=10)),
                ('external_link_label', models.CharField(blank=True, max_length=100)),
                ('external_link_url', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'About Section',
                'verbose_name_plural': 'About Sections',
                'ordering': ['order', 'section_key'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_key', models.CharField(choices=[('innovation', 'Innovation'), ('curiosity', 'Curiosity'), ('leadership', 'Leadership'), ('collaboration', 'Collaboration'), ('creativity', 'Creativity'), ('impact', 'Community Impact'), ('mission', 'Mission'), ('vision', 'Vision')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('message_type', models.CharField(choices=[('president', 'President'), ('organizer', 'Organizer'), ('vice_president', 'Vice President')], max_length=20, unique=True)),
                ('person_name', models.CharField(max_length=200)),
                ('role_title', models.CharField(help_text='e.g. President & Official Organizer · TEDxUMT Lahore', max_length=200)),
                ('message_body', models.TextField()),
                ('photo', models.ImageField(blank=True, help_text='Portrait photo. Will appear beside the quote.', upload_to='messages/')),
                ('is_visible', models.BooleanField(default=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages (President / Organizer)',
                'ordering': ['order', 'message_type'],
            },
        ),
    ]
