# Generated by Django 5.2.17 on 2026-08-31 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('founder', 'Founder'), ('president', 'President'), ('organizer', 'Organizer'), ('vice_president', 'Vice President')], max_length=20, unique=True),
        ),
    ]
