# Generated by Django 5.2.17 on 2026-09-02 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_message_message_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['order', 'message_type'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages (Founder / President / Organizer)'},
        ),
    ]
