# Generated by Django 5.2.17 on 2026-09-03 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_alter_message_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Founder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('role_title', models.CharField(default='Founder · TEDxUMT Lahore', help_text='Shown under the name, e.g. Founder & Licensee · TEDxUMT Lahore', max_length=200)),
                ('photo', models.ImageField(blank=True, help_text='Portrait. A tall crop works best — it sits beside the story.', upload_to='founder/')),
                ('story', models.TextField(help_text='The founder’s story. Leave a blank line between paragraphs.')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('is_visible', models.BooleanField(default=True, help_text='Untick to hide the Founder page without deleting anything.')),
            ],
            options={
                'verbose_name': 'Founder',
                'verbose_name_plural': 'Founder',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['order', 'message_type'], 'verbose_name': 'Message', 'verbose_name_plural': 'Messages (President / Organizer)'},
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('president', 'President'), ('organizer', 'Organizer'), ('vice_president', 'Vice President')], max_length=20, unique=True),
        ),
    ]
